### ISSUE TITLE
Routes do not transition when used with guardians

### ISSUE THREAD

**Issue by rafikmoreira** [Upstatement/react-router-guards#77]
# Summary
Goodnight. I'm using the react-router-dom package, with it I can animate the transition between my application's routes, however, when I add guardians to the routes they stop showing the transition. Does anyone know how I can get around this?
## Relevant information

Provide as much useful information as you can
"react-router-dom": "^5.2.0",
"react-router-guards": "^1.0.2",
"react-transition-group": "^4.4.2",

**Comment by vtrphan** [comment]
i'm having this problem too

**Comment by joshpensky** [comment]
Unfortunately, this is one downside of using React Router Guards (and one we should probably surface in the README)—since we do a lot of component switching in our `GuardedRoute` components, transition libraries like `react-transition-group` have trouble detecting which components to transition and thus aren't compatible

Feel free to re-open the conversation if you have any further questions!

**Comment by vtrphan** [comment]
Do you have any suggestion how we can implement route transition to work with react-router-guard?
